<a href="https://colab.research.google.com/github/nitron-alpha-kplr/Generative-IA/blob/main/6.GPT/gpt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🚀 GPT

In this notebook, we'll walk through the steps required to train your own GPT model on the wine review dataset

The code is adapted from the excellent [GPT tutorial](https://keras.io/examples/generative/text_generation_with_miniature_gpt/) created by Apoorv Nandan available on the Keras website.

In [ ]:
import autoreload
?autoreload
# Then you get all the above

In [ ]:
%load_ext autoreload
%autoreload 2
import numpy as np
import json
import re
import string
from IPython.display import display, HTML

import tensorflow as tf
from tensorflow.keras import layers, models, losses, callbacks

## 0. Parameters <a name="parameters"></a>

In [ ]:
VOCAB_SIZE = 10000
MAX_LEN = 80
EMBEDDING_DIM = 256
KEY_DIM = 256
N_HEADS = 2
FEED_FORWARD_DIM = 256
VALIDATION_SPLIT = 0.2
SEED = 42
LOAD_MODEL = False
BATCH_SIZE = 32
EPOCHS = 5

## 1. Load the data <a name="load"></a>

In [14]:
# Load the full dataset
with open("/content/winemag-data-130k-v2.json") as json_data:
    wine_data = json.load(json_data)

In [15]:
wine_data[10]

{'points': '87',
 'title': 'Kirkland Signature 2011 Mountain Cuvée Cabernet Sauvignon (Napa Valley)',
 'description': 'Soft, supple plum envelopes an oaky structure in this Cabernet, supported by 15% Merlot. Coffee and chocolate complete the picture, finishing strong at the end, resulting in a value-priced wine of attractive flavor and immediate accessibility.',
 'taster_name': 'Virginie Boone',
 'taster_twitter_handle': '@vboone',
 'price': 19,
 'designation': 'Mountain Cuvée',
 'variety': 'Cabernet Sauvignon',
 'region_1': 'Napa Valley',
 'region_2': 'Napa',
 'province': 'California',
 'country': 'US',
 'winery': 'Kirkland Signature'}

In [16]:
# Filter the dataset
filtered_data = [
    "wine review : "
    + x["country"]
    + " : "
    + x["province"]
    + " : "
    + x["variety"]
    + " : "
    + x["description"]
    for x in wine_data
    if x["country"] is not None
    and x["province"] is not None
    and x["variety"] is not None
    and x["description"] is not None
]

In [17]:
# Count the recipes
n_wines = len(filtered_data)
print(f"{n_wines} recipes loaded")

129907 recipes loaded


In [18]:
example = filtered_data[25]
print(example)

wine review : US : California : Pinot Noir : Oak and earth intermingle around robust aromas of wet forest floor in this vineyard-designated Pinot that hails from a high-elevation site. Small in production, it offers intense, full-bodied raspberry and blackberry steeped in smoky spice and smooth texture.


## 2. Tokenize the data <a name="tokenize"></a>

In [19]:
# Pad the punctuation, to treat them as separate 'words'
def pad_punctuation(s):
    s = re.sub(f"([{string.punctuation}, '\n'])", r" \1 ", s)
    s = re.sub(" +", " ", s)
    return s


text_data = [pad_punctuation(x) for x in filtered_data]

In [20]:
# Display an example of a recipe
example_data = text_data[25]
example_data

'wine review : US : California : Pinot Noir : Oak and earth intermingle around robust aromas of wet forest floor in this vineyard - designated Pinot that hails from a high - elevation site . Small in production , it offers intense , full - bodied raspberry and blackberry steeped in smoky spice and smooth texture . '

In [21]:
# Convert to a Tensorflow Dataset
text_ds = (
    tf.data.Dataset.from_tensor_slices(text_data)
    .batch(BATCH_SIZE)
    .shuffle(1000)
)

In [22]:
# Create a vectorisation layer
vectorize_layer = layers.TextVectorization(
    standardize="lower",
    max_tokens=VOCAB_SIZE,
    output_mode="int",
    output_sequence_length=MAX_LEN + 1,
)

In [23]:
# Adapt the layer to the training set
vectorize_layer.adapt(text_ds)
vocab = vectorize_layer.get_vocabulary()

In [24]:
# Display some token:word mappings
for i, word in enumerate(vocab[:10]):
    print(f"{i}: {word}")

0: 
1: [UNK]
2: :
3: ,
4: .
5: and
6: the
7: wine
8: a
9: of


In [25]:
# Display the same example converted to ints
example_tokenised = vectorize_layer(example_data)
print(example_tokenised.numpy())

[   7   10    2   20    2   29    2   43   62    2   55    5  243 4145
  453  634   26    9  497  499  667   17   12  142   14 2214   43   25
 2484   32    8  223   14 2213  948    4  594   17  987    3   15   75
  237    3   64   14   82   97    5   74 2633   17  198   49    5  125
   77    4    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0]


## 3. Create the Training Set <a name="create"></a>

In [26]:
# Create the training set of recipes and the same text shifted by one word
def prepare_inputs(text):
    text = tf.expand_dims(text, -1)
    tokenized_sentences = vectorize_layer(text)
    x = tokenized_sentences[:, :-1]
    y = tokenized_sentences[:, 1:]
    return x, y


train_ds = text_ds.map(prepare_inputs)

In [27]:
example_input_output = train_ds.take(1).get_single_element()

In [28]:
# Example Input
example_input_output[0][0]

<tf.Tensor: shape=(80,), dtype=int64, numpy=
array([   7,   10,    2,   20,    2,  103,    2,   45,   44,    2,  703,
         32,    6,  409,   18,   21,  337,  142,  223,  117,   17, 3316,
       5108, 1377,    3,   12,    7,   13, 1493,   19,  259,    8,  153,
          9,  158,    3,  355,   26,    9,  333,    3,  114,   36,    3,
         94,   90,    5, 1101, 2263,    4, 1071, 1149,   78,    5,   94,
          3,    6,   16,  241,  227,    8,  153, 2321,    3,   11, 1017,
         14,   90,   50,   23,    6,   31,    4,    0,    0,    0,    0,
          0,    0,    0])>

In [29]:
# Example Output (shifted by one token)
example_input_output[1][0]

<tf.Tensor: shape=(80,), dtype=int64, numpy=
array([  10,    2,   20,    2,  103,    2,   45,   44,    2,  703,   32,
          6,  409,   18,   21,  337,  142,  223,  117,   17, 3316, 5108,
       1377,    3,   12,    7,   13, 1493,   19,  259,    8,  153,    9,
        158,    3,  355,   26,    9,  333,    3,  114,   36,    3,   94,
         90,    5, 1101, 2263,    4, 1071, 1149,   78,    5,   94,    3,
          6,   16,  241,  227,    8,  153, 2321,    3,   11, 1017,   14,
         90,   50,   23,    6,   31,    4,    0,    0,    0,    0,    0,
          0,    0,    0])>

## 5. Create the causal attention mask function <a name="causal"></a>

In [30]:
def causal_attention_mask(batch_size, n_dest, n_src, dtype):
    i = tf.range(n_dest)[:, None]
    j = tf.range(n_src)
    m = i >= j - n_src + n_dest
    mask = tf.cast(m, dtype)
    mask = tf.reshape(mask, [1, n_dest, n_src])
    mult = tf.concat(
        [tf.expand_dims(batch_size, -1), tf.constant([1, 1], dtype=tf.int32)], 0
    )
    return tf.tile(mask, mult)


np.transpose(causal_attention_mask(1, 10, 10, dtype=tf.int32)[0])

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int32)

## 6. Create a Transformer Block layer <a name="transformer"></a>

In [31]:
class TransformerBlock(layers.Layer):
    def __init__(self, num_heads, key_dim, embed_dim, ff_dim, dropout_rate=0.1):
        super(TransformerBlock, self).__init__()
        self.num_heads = num_heads
        self.key_dim = key_dim
        self.embed_dim = embed_dim
        self.ff_dim = ff_dim
        self.dropout_rate = dropout_rate
        self.attn = layers.MultiHeadAttention(
            num_heads, key_dim, output_shape=embed_dim
        )
        self.dropout_1 = layers.Dropout(self.dropout_rate)
        self.ln_1 = layers.LayerNormalization(epsilon=1e-6)
        self.ffn_1 = layers.Dense(self.ff_dim, activation="relu")
        self.ffn_2 = layers.Dense(self.embed_dim)
        self.dropout_2 = layers.Dropout(self.dropout_rate)
        self.ln_2 = layers.LayerNormalization(epsilon=1e-6)

    def call(self, inputs):
        input_shape = tf.shape(inputs)
        batch_size = input_shape[0]
        seq_len = input_shape[1]
        causal_mask = causal_attention_mask(
            batch_size, seq_len, seq_len, tf.bool
        )
        attention_output, attention_scores = self.attn(
            inputs,
            inputs,
            attention_mask=causal_mask,
            return_attention_scores=True,
        )
        attention_output = self.dropout_1(attention_output)
        out1 = self.ln_1(inputs + attention_output)
        ffn_1 = self.ffn_1(out1)
        ffn_2 = self.ffn_2(ffn_1)
        ffn_output = self.dropout_2(ffn_2)
        return (self.ln_2(out1 + ffn_output), attention_scores)

    def get_config(self):
        config = super().get_config()
        config.update(
            {
                "key_dim": self.key_dim,
                "embed_dim": self.embed_dim,
                "num_heads": self.num_heads,
                "ff_dim": self.ff_dim,
                "dropout_rate": self.dropout_rate,
            }
        )
        return config

## 7. Create the Token and Position Embedding <a name="embedder"></a>

In [32]:
class TokenAndPositionEmbedding(layers.Layer):
    def __init__(self, max_len, vocab_size, embed_dim):
        super(TokenAndPositionEmbedding, self).__init__()
        self.max_len = max_len
        self.vocab_size = vocab_size
        self.embed_dim = embed_dim
        self.token_emb = layers.Embedding(
            input_dim=vocab_size, output_dim=embed_dim
        )
        self.pos_emb = layers.Embedding(input_dim=max_len, output_dim=embed_dim)

    def call(self, x):
        maxlen = tf.shape(x)[-1]
        positions = tf.range(start=0, limit=maxlen, delta=1)
        positions = self.pos_emb(positions)
        x = self.token_emb(x)
        return x + positions

    def get_config(self):
        config = super().get_config()
        config.update(
            {
                "max_len": self.max_len,
                "vocab_size": self.vocab_size,
                "embed_dim": self.embed_dim,
            }
        )
        return config

## 8. Build the Transformer model <a name="transformer_decoder"></a>

In [33]:
inputs = layers.Input(shape=(None,), dtype=tf.int32)
x = TokenAndPositionEmbedding(MAX_LEN, VOCAB_SIZE, EMBEDDING_DIM)(inputs)
x, attention_scores = TransformerBlock(
    N_HEADS, KEY_DIM, EMBEDDING_DIM, FEED_FORWARD_DIM
)(x)
outputs = layers.Dense(VOCAB_SIZE, activation="softmax")(x)
gpt = models.Model(inputs=inputs, outputs=[outputs, attention_scores])
gpt.compile("adam", loss=[losses.SparseCategoricalCrossentropy(), None])

In [34]:
gpt.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, None)]            0         
                                                                 
 token_and_position_embeddi  (None, None, 256)         2580480   
 ng (TokenAndPositionEmbedd                                      
 ing)                                                            
                                                                 
 transformer_block (Transfo  ((None, None, 256),       658688    
 rmerBlock)                   (None, 2, None, None))             
                                                                 
 dense_2 (Dense)             (None, None, 10000)       2570000   
                                                                 
Total params: 5809168 (22.16 MB)
Trainable params: 5809168 (22.16 MB)
Non-trainable params: 0 (0.00 Byte)
_____________________

In [35]:
if LOAD_MODEL:
    # model.load_weights('./models/model')
    gpt = models.load_model("./models/gpt", compile=True)

## 9. Train the Transformer <a name="train"></a>

In [36]:
# Create a TextGenerator checkpoint
class TextGenerator(callbacks.Callback):
    def __init__(self, index_to_word, top_k=10):
        self.index_to_word = index_to_word
        self.word_to_index = {
            word: index for index, word in enumerate(index_to_word)
        }

    def sample_from(self, probs, temperature):
        probs = probs ** (1 / temperature)
        probs = probs / np.sum(probs)
        return np.random.choice(len(probs), p=probs), probs

    def generate(self, start_prompt, max_tokens, temperature):
        start_tokens = [
            self.word_to_index.get(x, 1) for x in start_prompt.split()
        ]
        sample_token = None
        info = []
        while len(start_tokens) < max_tokens and sample_token != 0:
            x = np.array([start_tokens])
            y, att = self.model.predict(x, verbose=0)
            sample_token, probs = self.sample_from(y[0][-1], temperature)
            info.append(
                {
                    "prompt": start_prompt,
                    "word_probs": probs,
                    "atts": att[0, :, -1, :],
                }
            )
            start_tokens.append(sample_token)
            start_prompt = start_prompt + " " + self.index_to_word[sample_token]
        print(f"\ngenerated text:\n{start_prompt}\n")
        return info

    def on_epoch_end(self, epoch, logs=None):
        self.generate("wine review", max_tokens=80, temperature=1.0)

In [37]:
# Create a model save checkpoint
model_checkpoint_callback = callbacks.ModelCheckpoint(
    filepath="./checkpoint/checkpoint.ckpt",
    save_weights_only=True,
    save_freq="epoch",
    verbose=0,
)

tensorboard_callback = callbacks.TensorBoard(log_dir="./logs")

# Tokenize starting prompt
text_generator = TextGenerator(vocab)

In [38]:
gpt.fit(
    train_ds,
    epochs=EPOCHS,
    callbacks=[model_checkpoint_callback, tensorboard_callback, text_generator],
)

Epoch 1/5
4060/4060 [==============================] - ETA: 0s - loss: 2.2520 - dense_2_loss: 2.2520
generated text:
wine review : austria : niederösterreich : grüner veltliner : touch of mint and green fruit appear on the nose , following a hybrid with notes of freshly cut red apple illuminates here . if the result is comprised , very soft and rounded , a super tuscan expression . 

4060/4060 [==============================] - 5496s 1s/step - loss: 2.2520 - dense_2_loss: 2.2520
Epoch 2/5
4060/4060 [==============================] - ETA: 0s - loss: 1.9590 - dense_2_loss: 1.9590
generated text:
wine review : france : bordeaux : bordeaux - style red blend : this is a supple , opulent wine dominated by smoky tannins , black currants and wood . it 2005 comes from a fresh , rustic wine , but it ' s not . 

4060/4060 [==============================] - 5491s 1s/step - loss: 1.9590 - dense_2_loss: 1.9590
Epoch 3/5
4060/4060 [==============================] - ETA: 0s - loss: 1.8890 - dense_2_lo

In [39]:
# Save the final model
gpt.save("./models/gpt")

# 3. Generate text using the Transformer

In [40]:
def print_probs(info, vocab, top_k=5):
    for i in info:
        highlighted_text = []
        for word, att_score in zip(
            i["prompt"].split(), np.mean(i["atts"], axis=0)
        ):
            highlighted_text.append(
                '<span style="background-color:rgba(135,206,250,'
                + str(att_score / max(np.mean(i["atts"], axis=0)))
                + ');">'
                + word
                + "</span>"
            )
        highlighted_text = " ".join(highlighted_text)
        display(HTML(highlighted_text))

        word_probs = i["word_probs"]
        p_sorted = np.sort(word_probs)[::-1][:top_k]
        i_sorted = np.argsort(word_probs)[::-1][:top_k]
        for p, i in zip(p_sorted, i_sorted):
            print(f"{vocab[i]}:   \t{np.round(100*p,2)}%")
        print("--------\n")

In [41]:
info = text_generator.generate(
    "wine review : us", max_tokens=80, temperature=1.0
)


generated text:
wine review : us : oregon : pinot noir : aromatic raspberries , cherries , berries and greens mix with red rose petals , rosewater and a touch of earthy funk . there ' s a hint of bark on the edges comes through on the finish . though gripping and tough . 



In [42]:
info = text_generator.generate(
    "wine review : italy", max_tokens=80, temperature=0.5
)


generated text:
wine review : italy : tuscany : sangiovese : this opens with aromas of dark - skinned berry , blue flower and a whiff of baking spice . the robust palate doles out black cherry , crushed raspberry , white pepper and a hint of pipe tobacco alongside firm but refined tannins . it ' s already accessible so enjoy soon . 



In [43]:
info = text_generator.generate(
    "wine review : germany", max_tokens=80, temperature=0.5
)
print_probs(info, vocab)


generated text:
wine review : germany : mosel : riesling : whiffs of smoke and slate lend earthiness to this full - bodied , semi - sweet riesling . it ' s ripe , sweet and honeyed , with peach and apricot flavors . it ' s a straightforward yet delectably juicy wine that ' s easy to enjoy . 



::   	100.0%
zealand:   	0.0%
-:   	0.0%
grosso:   	0.0%
blend:   	0.0%
--------



mosel:   	75.28%
rheingau:   	22.75%
pfalz:   	0.84%
rheinhessen:   	0.62%
franken:   	0.28%
--------



::   	99.17%
-:   	0.83%
valley:   	0.0%
blanca:   	0.0%
hills:   	0.0%
--------



riesling:   	100.0%
spätburgunder:   	0.0%
weissburgunder:   	0.0%
pinot:   	0.0%
white:   	0.0%
--------



::   	100.0%
-:   	0.0%
blanc:   	0.0%
grosso:   	0.0%
du:   	0.0%
--------



a:   	21.8%
whiffs:   	18.71%
while:   	12.16%
this:   	8.27%
hints:   	7.81%
--------



of:   	100.0%
suggesting:   	0.0%
recall:   	0.0%
suggest:   	0.0%
evoking:   	0.0%
--------



smoke:   	76.29%
saffron:   	8.56%
crushed:   	5.31%
honey:   	2.61%
slate:   	1.47%
--------



and:   	98.23%
,:   	1.76%
lends:   	0.0%
lend:   	0.0%
blow:   	0.0%
--------



slate:   	75.58%
crushed:   	14.08%
smoke:   	2.94%
bramble:   	0.87%
struck:   	0.87%
--------



lend:   	97.71%
add:   	1.44%
meld:   	0.17%
are:   	0.13%
extend:   	0.08%
--------



a:   	54.72%
complexity:   	18.18%
savory:   	10.17%
earthiness:   	7.03%
nuance:   	2.69%
--------



to:   	99.98%
and:   	0.02%
,:   	0.0%
.:   	0.0%
on:   	0.0%
--------



this:   	87.0%
the:   	9.08%
pristine:   	2.57%
fresh:   	0.45%
ripe:   	0.25%
--------



dry:   	30.79%
off:   	13.45%
semi:   	11.38%
intensely:   	10.15%
otherwise:   	7.59%
--------



-:   	99.96%
,:   	0.04%
wine:   	0.0%
and:   	0.0%
riesling:   	0.0%
--------



bodied:   	100.0%
and:   	0.0%
on:   	0.0%
footed:   	0.0%
force:   	0.0%
--------



,:   	54.77%
riesling:   	31.41%
wine:   	8.97%
dry:   	4.5%
and:   	0.09%
--------



dry:   	57.85%
intensely:   	9.59%
richly:   	5.23%
ripe:   	4.98%
off:   	3.56%
--------



-:   	100.0%
dry:   	0.0%
sweet:   	0.0%
riesling:   	0.0%
white:   	0.0%
--------



sweet:   	98.34%
dry:   	1.61%
concentrated:   	0.01%
bodied:   	0.01%
ripe:   	0.01%
--------



riesling:   	98.79%
wine:   	0.8%
spätlese:   	0.21%
auslese:   	0.11%
white:   	0.04%
--------



.:   	99.97%
that:   	0.03%
,:   	0.0%
from:   	0.0%
and:   	0.0%
--------



it:   	89.88%
the:   	6.51%
ripe:   	1.52%
hints:   	0.17%
juicy:   	0.13%
--------



':   	99.99%
balances:   	0.0%
is:   	0.0%
has:   	0.0%
offers:   	0.0%
--------



s:   	100.0%
ll:   	0.0%
[UNK]:   	0.0%
dry:   	0.0%
of:   	0.0%
--------



juicy:   	18.42%
intensely:   	14.06%
rich:   	11.3%
a:   	9.24%
ripe:   	9.24%
--------



and:   	81.79%
,:   	10.38%
with:   	6.42%
in:   	0.41%
on:   	0.4%
--------



with:   	58.98%
juicy:   	8.18%
sweet:   	8.01%
honeyed:   	6.16%
yet:   	5.22%
--------



and:   	87.61%
,:   	3.95%
-:   	2.66%
in:   	1.93%
on:   	1.65%
--------



honeyed:   	76.63%
luscious:   	5.46%
juicy:   	3.96%
rich:   	2.59%
succulent:   	2.13%
--------



,:   	42.19%
on:   	25.34%
with:   	25.19%
in:   	5.8%
yet:   	1.04%
--------



with:   	74.57%
but:   	19.4%
yet:   	4.54%
it:   	1.08%
and:   	0.07%
--------



a:   	42.26%
hints:   	24.97%
loads:   	8.84%
notes:   	5.67%
sweet:   	3.77%
--------



and:   	96.6%
,:   	3.36%
nectar:   	0.03%
flavors:   	0.01%
-:   	0.0%
--------



apricot:   	37.37%
tangerine:   	18.75%
honey:   	13.35%
mango:   	8.35%
melon:   	6.66%
--------



flavors:   	96.79%
notes:   	2.53%
nectar:   	0.57%
aromas:   	0.04%
,:   	0.04%
--------



,:   	59.93%
that:   	19.2%
.:   	15.39%
accented:   	3.54%
on:   	0.71%
--------



it:   	94.34%
the:   	3.57%
a:   	1.21%
:   	0.17%
drink:   	0.14%
--------



':   	99.98%
finishes:   	0.01%
penetrates:   	0.0%
is:   	0.0%
lingers:   	0.0%
--------



s:   	100.0%
ll:   	0.0%
[UNK]:   	0.0%
sweet:   	0.0%
sugar:   	0.0%
--------



a:   	39.82%
juicy:   	9.36%
full:   	7.41%
rich:   	7.27%
lush:   	4.22%
--------



bit:   	27.26%
juicy:   	11.04%
straightforward:   	9.15%
bold:   	8.0%
touch:   	6.61%
--------



,:   	63.55%
yet:   	24.09%
wine:   	7.45%
but:   	2.78%
quaffer:   	1.36%
--------



delectably:   	52.93%
elegantly:   	8.21%
balanced:   	7.08%
approachable:   	6.21%
deeply:   	5.76%
--------



juicy:   	92.41%
fruity:   	4.21%
composed:   	2.24%
quaffable:   	0.34%
easy:   	0.24%
--------



wine:   	53.83%
,:   	41.98%
and:   	3.16%
riesling:   	0.4%
with:   	0.16%
--------



that:   	36.63%
with:   	26.27%
.:   	16.74%
,:   	14.18%
to:   	4.87%
--------



':   	87.49%
finishes:   	3.52%
would:   	2.48%
should:   	2.33%
will:   	1.59%
--------



s:   	100.0%
ll:   	0.0%
[UNK]:   	0.0%
refreshing:   	0.0%
d:   	0.0%
--------



balanced:   	25.59%
easy:   	18.09%
refreshing:   	9.01%
a:   	4.83%
quaffable:   	4.35%
--------



to:   	98.5%
drinking:   	1.03%
and:   	0.29%
-:   	0.09%
on:   	0.05%
--------



enjoy:   	95.8%
drink:   	3.84%
sip:   	0.32%
like:   	0.02%
find:   	0.01%
--------



now:   	69.11%
.:   	26.97%
with:   	2.31%
and:   	0.6%
,:   	0.55%
--------



:   	99.73%
drink:   	0.13%
enjoy:   	0.1%
it:   	0.03%
the:   	0.0%
--------

